services:
  zenful_shopping_backend:
    build: .
    container_name: zenful_shopping_backend
    environment:
      - ADDR=${ADDR}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_ADDR=${DB_ADDR}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GOOGLE_TOKEN=${GOOGLE_TOKEN}
      - GOOGLE_USERNAME=${GOOGLE_USERNAME}
    volumes:
      - ${FILE_STORAGE_PATH}:/app/file_storage
    networks:
      - nginx_net
      - zenful_shopping

networks:
  nginx_net:
    external: true
  zenful_shopping:
    external: true
