CREATE TABLE Users (
    UserID SERIAL PRIMARY KEY,
    Username VARCHAR(255) UNIQUE NOT NULL,
    Email VARCHAR(255) UNIQUE NOT NULL,
    PasswordHash TEXT NOT NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Images (
    ImageID SERIAL PRIMARY KEY,
    FilePath VARCHAR(255) NOT NULL,
    UploadedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Recipes (
    RecipeID SERIAL PRIMARY KEY,
    Title VARCHAR(255) NOT NULL,
    UserID INT REFERENCES Users(UserID) ON DELETE CASCADE,
    Public BOOLEAN DEFAULT FALSE,
    Description TEXT,
    CookTime INT CHECK (CookTime >= 0),
    Servings INT CHECK (Servings >= 0),
    ImageID INT REFERENCES Images(ImageID) ON DELETE SET NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uc_Recipe UNIQUE (Title, UserID)
);

CREATE TABLE Ingredients (
    IngredientID SERIAL PRIMARY KEY,
    Name VARCHAR(255) UNIQUE NOT NULL,
    Description TEXT,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE MeasurementUnits (
    MeasurementUnitID SERIAL PRIMARY KEY,
    Name VARCHAR(255) UNIQUE NOT NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE RecipeIngredients (
    RecipeIngredientID SERIAL PRIMARY KEY,
    RecipeID INT REFERENCES Recipes(RecipeID) ON DELETE CASCADE,
    IngredientID INT REFERENCES Ingredients(IngredientID) ON DELETE CASCADE,
    Quantity FLOAT NOT NULL CHECK (Quantity > 0),
    MeasurementUnitID INT REFERENCES MeasurementUnits(MeasurementUnitID),
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Instructions (
    InstructionID SERIAL PRIMARY KEY,
    Content TEXT NOT NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE RecipeInstructions (
    RecipeInstructionID SERIAL PRIMARY KEY,
    RecipeID INT REFERENCES Recipes(RecipeID) ON DELETE CASCADE,
    InstructionID INT REFERENCES Instructions(InstructionID) ON DELETE CASCADE,
    Numbering INT NOT NULL CHECK (Numbering > 0),
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE MealTypes (
    MealTypeID SERIAL PRIMARY KEY,
    Name VARCHAR(255) UNIQUE NOT NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE RecipeMealTypes (
    RecipeMealTypeID SERIAL PRIMARY KEY,
    RecipeID INT REFERENCES Recipes(RecipeID) ON DELETE CASCADE,
    MealTypeID INT REFERENCES MealTypes(MealTypeID) ON DELETE CASCADE,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE FoodGroups (
    FoodGroupID SERIAL PRIMARY KEY,
    Name VARCHAR(255) UNIQUE NOT NULL,
    Description TEXT,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ShoppingLists (
    ShoppingListID SERIAL PRIMARY KEY,
    UserID INT REFERENCES Users(UserID) ON DELETE CASCADE,
    Name VARCHAR(255) NOT NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ShoppingListItems (
    ShoppingListItemID SERIAL PRIMARY KEY,
    ShoppingListID INT REFERENCES ShoppingLists(ShoppingListID) ON DELETE CASCADE,
    IngredientID INT REFERENCES Ingredients(IngredientID) ON DELETE CASCADE,
    MeasurementUnitID INT REFERENCES MeasurementUnits(MeasurementUnitID) ON DELETE CASCADE,
    Quantity FLOAT NOT NULL CHECK (Quantity > 0),
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE UserIngredients (
    UserIngredientID SERIAL PRIMARY KEY,
    UserID INT REFERENCES Users(UserID) ON DELETE CASCADE,
    IngredientID INT REFERENCES Ingredients(IngredientID) ON DELETE CASCADE,
    Favorite BOOLEAN DEFAULT FALSE,
    FavoriteSortPosition INT DEFAULT 0 CHECK (FavoriteSortPosition >= 0),
    Pantry BOOLEAN DEFAULT FALSE,
    PantrySortPosition INT DEFAULT 0 CHECK (PantrySortPosition >= 0),
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
