name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create .env file
        run: |
          cat > .env << EOF
          ADDR=${{ secrets.ADDR }}
          DB_HOST=${{ secrets.DB_HOST }}
          DB_PORT=${{ secrets.DB_PORT }}
          DB_USER=${{ secrets.DB_USER }}
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          DB_NAME=${{ secrets.DB_NAME }}
          DB_ADDR=${{ secrets.DB_ADDR }}
          OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
          GOOGLE_TOKEN=${{ secrets.GOOGLE_TOKEN }}
          GOOGLE_USERNAME=${{ secrets.GOOGLE_USERNAME }}
          EOF
      - name: Deploy with Docker Compose
        run: |
          docker compose down || true
          docker compose up -d --build
